### ISSUE TITLE
[Icon Request]: PowerPanel

### ISSUE THREAD

**Issue by 0xEmma** [WalkxCode/dashboard-icons#1]
**What is the name of the icon?**
[Eg. Portainer]
PowerPanel
**What is the website/page of the icon?**
[Eg. https://portainer.io]
https://www.cyberpowersystems.com/products/software/power-panel-personal/
**Upload the icon here: [Optional]**
Upload the icon, MUST be `PNG` or `SVG`.
https://static.macupdate.com/products/62583/l/cyberpower-powerpanel-personal-logo.png?v=1592649661
![image](https://user-images.githubusercontent.com/47154306/132999976-f5685cc6-99af-49ba-9e14-6fe8c407137d.png)

**Comment by WalkxCode** [comment]
Thanks for the suggestion, I'll add it ASAP!

**Comment by WalkxCode** [comment]
@0xEmma Added 👍🏻
