### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by CKraft11** [walkxcode/Dashboard-Icons#119]
### Type

Icon request

### Info

Type:
Icon request

Info
EdgeOS is the router portal for some Ubiquiti Products you could use the Unifi.png icon for this too and put it in twice if you want

Icon(s)
![image](https://user-images.githubusercontent.com/58564269/199095858-6a7dedc7-0496-4ae5-9336-c49b30b8a700.png)

### Icon(s)

![image](https://user-images.githubusercontent.com/58564269/199095871-bfbabe0c-f422-41d7-abc4-22403f11c2d5.png)

**Comment by walkxcode** [comment]
Hey, both EdgeOS and Unifi should both be in the repo already.
