### ISSUE TITLE
⚡ — rdtclient icon request

### ISSUE THREAD

**Issue by nanhoes** [walkxcode/Dashboard-Icons#120]
### Type

Icon request

### Info

Please add this rdtclient icon, thanks!

### Icon(s)

![rdtclient](https://user-images.githubusercontent.com/68497310/199144851-a81bb8c0-bbe1-4cc6-b9cd-22fb723c10bf.png)

**Comment by walkxcode** [comment]
Hey, can you give some more information about where this icon is from? Can't seem to find anything.

**Comment by nanhoes** [comment]
Sure, here’s the GitHub project: https://github.com/rogerfar/rdt-client
