### ISSUE TITLE
changedetection.io logo

### ISSUE THREAD

**Issue by Metallizer** [walkxcode/Dashboard-Icons#121]
### Info

https://www.cloudron.io/store/io.changedetection.cloudronapp.html

### Icon(s)

![changedetection](https://user-images.githubusercontent.com/24228218/199182895-dcccb3a5-278f-4c71-9d29-10c83a338ef0.svg)
![changedetection](https://user-images.githubusercontent.com/24228218/199182898-bcb6e3b1-9ebd-40dc-bb12-46db6ea5b10b.png)

**Comment by walkxcode** [comment]
Hey, changedetection doesn't seem to have any logo. Where'd you get this icon from?

**Comment by walkxcode** [comment]
@Metallizer reminder.

**Comment by itsprakashp** [comment]
@walkxcode https://github.com/dgtlmoon/changedetection.io/blob/master/changedetectionio/static/images/avatar-256x256.png
