### ISSUE TITLE
URL Broken

### ISSUE THREAD

**Issue by thorrrr** [walkxcode/Dashboard-Icons#151]
### Type

Documentation change

### Info

The url no longer works i tried https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/example.png  on several browsers wifi and 4g nothing !!!!

**Comment by walkxcode** [comment]
Hey, I think you're a bit confused here. That's just an example link. To grab an icon via jsdelivr, please replace "example.png" with the icon name from the repo.

**Comment by thorrrr** [comment]
> Hey, I think you're a bit confused here. That's just an example link. To grab an icon via jsdelivr, please replace "example.png" with the icon name from the repo. 

Yep worked it out sorry can I make a request for a WhatsApp icon please?
