### ISSUE TITLE
⚡ — Add icons

### ISSUE THREAD

**Issue by LuckyS7evin** [walkxcode/Dashboard-Icons#153]
### Type

Icon request

### Info

Hi,
Can you please add the following icons ?

- FireShare : https://github.com/ShaneIsrael/fireshare
- WatchYourLan : https://github.com/aceberg/WatchYourLAN
- CasaOS : https://github.com/IceWhaleTech/CasaOS
- Gladys Assistant : https://github.com/GladysAssistant/Gladys

 Thank you in advance

Let me know if you prefer I add icons on this issue

**Comment by walkxcode** [comment]
Hey, can't seem to find a transparent icon for CasaOS. Do you have one?

**Comment by LuckyS7evin** [comment]
No I can't find one, Forgive about CasaOS, it's not important
