### ISSUE TITLE
New door

### ISSUE THREAD

**Issue by Kilthor** [walkxcode/Dashboard-Icons#164]
### Type

Icon enhancement

### Info

How's this ?
I can keep playing with it
Learning adobe

### Icon(s)

![bdtesthd](https://user-images.githubusercontent.com/45773233/202743033-d8531b6e-46ef-46a4-99c3-0be693f9e59a.png)

**Comment by walkxcode** [comment]
Hey, I think the old version looks a bit better (even though more blurry). I will keep this issue open for if you have any future changes.

**Comment by Kilthor** [comment]
My apology I forgot what was originally needed fixing. Resolution I think? 
I am assuming you like the square corners better then the rounded?
I sharpened the 600 and resized to 1000 here's both
Let me know your thoughts
![bd1000hd](https://user-images.githubusercontent.com/45773233/204100266-bdffb475-e7b1-44cf-9e10-8c5612848750.png)
![bd600hd](https://user-images.githubusercontent.com/45773233/204100268-d5fbe19c-0752-4171-8975-018d2ca5a15b.png)
