### ISSUE TITLE
Draytek icon

### ISSUE THREAD

**Issue by HenrysCat** [walkxcode/Dashboard-Icons#165]
### Type

Icon request

### Info

Please add Draytek icon

### Icon(s)

![draytek](https://user-images.githubusercontent.com/47726287/202804043-e9ed29c4-e1ae-415c-90ca-d177a4dcadbd.png)

**Comment by walkxcode** [comment]
Hey, where did you find this icon? I can't seem to find anything that verifies this is the correct icon.

**Comment by HenrysCat** [comment]
It’s the favicon from the Draytek website.

On 19 Nov 2022, at 12:45, Bjorn Lammers ***@***.***> wrote:

﻿

Hey, where did you find this icon? I can't seem to find anything that verifies this is the correct icon.
