### ISSUE TITLE
⚡ — add Helium (HNT) crypto icon

### ISSUE THREAD

**Issue by HenrysCat** [walkxcode/Dashboard-Icons#170]
### Type

Icon request

### Info

Plase add Helium (HNT) crypto icon

### Icon(s)

![helium-hnt-logo](https://user-images.githubusercontent.com/47726287/202921102-ffedd8b9-041a-4afe-af6f-69def45c33c8.png)

**Comment by walkxcode** [comment]
Hey, do you want me to add the file as `hnt`, `helium`, or `helium-token`?

**Comment by HenrysCat** [comment]
I think helium-token, let's people know exactly what it intended for.
