### ISSUE TITLE
⚡ — new icons

### ISSUE THREAD

**Issue by 3vilson** [walkxcode/dashboard-icons#192]
### Type

Icon request

### Info

Some different styles

### Icon(s)

![wled2](https://user-images.githubusercontent.com/68461131/206272299-4497fab9-3a1d-4185-a303-99a474aae8cf.png)
![filebrowser](https://user-images.githubusercontent.com/68461131/206272304-974d7798-6c05-45f8-b545-8fa52354a8a2.png)
![github](https://user-images.githubusercontent.com/68461131/206272307-5ad95336-dac6-48bf-8173-1c4826fbbf69.png)
![mariadb-icon](https://user-images.githubusercontent.com/68461131/206272310-b4ad8183-5f2e-4edd-9523-af9a1edcc60e.png)
![pihole-unbound](https://user-images.githubusercontent.com/68461131/206272314-6c218de8-6f58-49f6-b870-80efb8cdfa55.png)
![portainer](https://user-images.githubusercontent.com/68461131/206272317-806319f6-1242-4af9-a9ed-99463f3d3819.png)
![reddit](https://user-images.githubusercontent.com/68461131/206272318-7bc399f5-94cd-4340-b9cc-93e2c2bb1d0f.png)
![rpi_monitor](https://user-images.githubusercontent.com/68461131/206272319-541d5a3e-8b92-4a20-b2be-6f9a2d3ea254.png)
![rustdesk](https://user-images.githubusercontent.com/68461131/206272321-282f6910-88b8-43dc-a4e9-912daf77a616.png)
![shell](https://user-images.githubusercontent.com/68461131/206272323-3e8e5556-96c8-48bf-b25f-e7c4b3e4cefe.png)
![voron](https://user-images.githubusercontent.com/68461131/206272326-c9fe7efc-4700-462b-a455-72502426b340.png)

**Comment by walkxcode** [comment]
Hey, I am very busy at the moment. If you'd like to, please make this into a pull request, otherwise it might take me a couple of days! 🙂
