### ISSUE TITLE
⚡ — Home Assistant

### ISSUE THREAD

**Issue by quentains** [walkxcode/dashboard-icons#197]
### Type

Icon request

### Info

Name: Home Assistant
URL: https://www.home-assistant.io/
Github: https://github.com/home-assistant/core

Thank you in advance !

### Icon(s)

![Home_Assistant_Logo](https://user-images.githubusercontent.com/15949162/207459769-46b72f6d-4980-4d6c-89bd-89e011b8bf43.svg)

**Comment by walkxcode** [comment]
Hello,
The repo already has home assistant added!

You can find them here:
https://github.com/walkxcode/dashboard-icons/blob/main/png/home-assistant.png
https://github.com/walkxcode/dashboard-icons/blob/main/png/home-assistant-circle.png
https://github.com/walkxcode/dashboard-icons/blob/main/svg/home-assistant.svg
