### ISSUE TITLE
⚡ — Add CodeStats icon

### ISSUE THREAD

**Issue by Enissay** [walkxcode/dashboard-icons#198]
### Type

Icon request

### Info

Please add Codestats icon

https://codestats.net/

### Icon(s)

![Logo-CodeStats](https://user-images.githubusercontent.com/794673/207487802-480a0b50-6c68-413f-a935-f2ec99859f04.svg)

**Comment by Enissay** [comment]
#199

**Comment by walkxcode** [comment]
Doing manually because of inactivity.
https://github.com/walkxcode/dashboard-icons/commit/9e1a0d2b92a3cefce9fdb0281d61f23fb3f265bd
