### ISSUE TITLE
⚡ — Real-Debrid Icon

### ISSUE THREAD

**Issue by c4rl3tt0** [walkxcode/dashboard-icons#203]
### Type

Icon request

### Info

Name: Real-Debrid
URL: https://real-debrid.com

Thank you!

### Icon(s)

![CrbDkDBt_400x400](https://user-images.githubusercontent.com/69254510/208237784-b5a85a90-e45c-4642-894a-450930a23ab4.png)

**Comment by walkxcode** [comment]
Hey, would you happen to have a PNG version of this icon?

**Comment by c4rl3tt0** [comment]
here you go
![rd](https://user-images.githubusercontent.com/69254510/208699563-a2786d80-a4d1-4992-a933-d6d81dab8a18.png)
