### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by tomnick** [walkxcode/dashboard-icons#208]
### Type

None

### Info

Trying to download and getting the following error:

`wget https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/example.png > example.png
--2022-12-29 13:08:59--  https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/example.png
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8000::154, 2606:50c0:8001::154, 2606:50c0:8002::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8000::154|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-12-29 13:08:59 ERROR 404: Not Found.
`

**Comment by MountainGod2** [comment]
That's a sample command and is failing because `example.png` doesn't actually exist. 

Try renaming it to an actual file that you want to download.

ex. `wget https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/github-light.png -O github-light.png`

**Comment by walkxcode** [comment]
Please see #151
