### ISSUE TITLE
TinyPilot Icon

### ISSUE THREAD

**Issue by szczottie** [walkxcode/dashboard-icons#219]
### Type

Icon request

### Info

Tiny Pilot Icon please ;)

### Icon(s)

![image](https://user-images.githubusercontent.com/77608863/211156535-69a5890a-d4bb-4926-8aed-74ce54980968.png)

**Comment by walkxcode** [comment]
Tinypilot was accidentally added in the wrong commit, but should be added now! https://github.com/walkxcode/dashboard-icons/commit/a6abfd85e1e14ba6eaf3086487c569de60ca7131
