### ISSUE TITLE
⚡ — Linuxserver.io

### ISSUE THREAD

**Issue by MasterSmurf** [walkxcode/dashboard-icons#220]
### Type

Icon request

### Info

The current linuxserver.io / lsio logo was decided [here](https://www.linuxserver.io/blog/2020-05-24-deciding-on-a-new-logo-by-abusing-everyone). It would be great to add the logo, because some images are using the lsio logo by default.

### Icon(s)

![lsio](https://user-images.githubusercontent.com/14371247/211203110-4a2bc082-e9db-4714-922c-017a3d92e6a2.svg)

**Comment by nomandera** [comment]
We endorse this message :)
