### ISSUE TITLE
Gigaset Icon⚡ — *put a quick title describing your issue here*

### ISSUE THREAD

**Issue by angeloschat** [walkxcode/dashboard-icons#222]
### Type

Icon request

### Info

https://www.gigaset.com/
Gigaset telephones, smart home etc.

### Icon(s)

![gigaset](https://user-images.githubusercontent.com/38050638/211628547-52bac1b4-8c50-40e8-aa5e-b5c03fe1f111.svg)

**Comment by walkxcode** [comment]
Hey, would you happen to have a 1:1 aspect ratio version of this logo?

**Comment by angeloschat** [comment]
Hi
I am afraid no. This is what I found on their website. I will try to find one.

**Comment by walkxcode** [comment]
Would you be okay with the icon being a bit smaller by adding empty space around it, so it's squared?

**Comment by angeloschat** [comment]
Sure. I could not find a proper 1:1 logo
