### ISSUE TITLE
Ionos Cloud provider⚡ — *put a quick title describing your issue here*

### ISSUE THREAD

**Issue by angeloschat** [walkxcode/dashboard-icons#223]
### Type

None

### Info

https://www.ionos.co.uk/ , https://ionos.eu/ , 
Cloud provider

### Icon(s)

![ionos](https://user-images.githubusercontent.com/38050638/211629338-e6cb0c0c-e2a1-44e1-a44d-49634829e38d.svg)

**Comment by walkxcode** [comment]
Hey, would you happen to have a 1:1 aspect ratio version of this logo?

**Comment by angeloschat** [comment]
Hi
I am afraid no. This is what I found on their website. I will try to find one.
