### ISSUE TITLE
Hetzner Cloud provider⚡ — *put a quick title describing your issue here*

### ISSUE THREAD

**Issue by angeloschat** [walkxcode/dashboard-icons#224]
### Type

None

### Info

https://www.hetzner.com/
Cloud provider

### Icon(s)

![logo-hetzner-online a4d06e5f6960b8dbaaf5481dc82b6789](https://user-images.githubusercontent.com/38050638/211630035-763a8c42-b7d1-422a-8154-cfb351813bb1.svg)

**Comment by walkxcode** [comment]
Hey, would you happen to have a 1:1 aspect ratio version of this logo?

**Comment by angeloschat** [comment]
Hi
I am afraid no. This is what I found on their website. I will try to find one.

**Comment by angeloschat** [comment]
![Hetz1](https://user-images.githubusercontent.com/38050638/212077327-5d7460dc-98c8-4b31-ab2d-c21e66d78f96.jpg)
![Hetz
![hetzner3](https://user-images.githubusercontent.com/38050638/212077490-b8a9f801-8af1-4d25-a426-b64823971f9d.jpg)
2](https://user-images.githubusercontent.com/38050638/212077344-654f0b96-1cb2-45a3-bcd0-cd5e368856aa.png)
