### ISSUE TITLE
Jira Icon

### ISSUE THREAD

**Issue by preetmakadia0** [walkxcode/dashboard-icons#233]
### Type

Icon request

### Info

Can you please add this Jira Icon?

### Icon(s)

<img width="32" alt="mark-gradient-blue-jira" src="https://user-images.githubusercontent.com/112287380/213895368-5d854de3-cad5-416c-8c46-739ccea308dc.png">

**Comment by mariushosting** [comment]
![Jira](https://user-images.githubusercontent.com/37554361/213903346-80f89575-6377-4199-92b7-0a609c8d9257.svg)
