### ISSUE TITLE
Atlassian Confluence

### ISSUE THREAD

**Issue by preetmakadia0** [walkxcode/dashboard-icons#234]
### Type

Icon request

### Info

Can you please add this Atlassian Confluence icon?

### Icon(s)

<img width="32" alt="mark-gradient-blue-confluence" src="https://user-images.githubusercontent.com/112287380/213895406-06af7f5e-63f7-4a9c-af5f-198ff52f126e.png">

**Comment by mariushosting** [comment]
![Confluence](https://user-images.githubusercontent.com/37554361/213903371-becf705d-0fac-4357-90b2-b82e78b9e8e4.svg)
