### ISSUE TITLE
Icon request for MeshCentral

### ISSUE THREAD

**Issue by bmcgonag** [walkxcode/dashboard-icons#24]
1st I love your collection, it is absolutely awesome, so thank you so much!

I'd like to request the addition of MeshCentral's icon as well as the Remotely icon to the collection.

Links to their pages are:

MeshCentral
https://www.meshcommander.com/meshcentral2

Remotely
https://github.com/immense/Remotely

I have a PNG, but no idea how to make an SVG, or I'd simply do a pull request.  So if you'd like to give me some pointers on making the SVG I would be happy to give it a shot as well.

**Comment by walkxcode** [comment]
An SVG is not required! I'll be happy if you'd make a pull request with just the PNG's

**Comment by V1P-J0K3R** [comment]
Meshcentral and Remotely Icon:
![meshcentral](https://user-images.githubusercontent.com/60364963/141183972-3fc4c02e-92d0-4842-91c4-f3d744d2e55d.png)
![remotely](https://user-images.githubusercontent.com/60364963/141183977-b0285146-7a09-44ed-a7a1-36df1df7eb38.png)

**Comment by walkxcode** [comment]
Hello, sorry for the late reply. Both icons have been added!
