### ISSUE TITLE
⚡ — Add ProtonMail, ProtonDrive, Proton Calendar, ProtonVPN

### ISSUE THREAD

**Issue by krintek** [walkxcode/dashboard-icons#246]
### Type

Icon request

### Info

https://proton.me/

Please add the icon for ProtonMail, ProtonDrive, Proton Calendar and ProtonVPN
![Screenshot_20230125-151906](https://user-images.githubusercontent.com/87629857/214531765-fc8a743d-27c5-4b60-ab5b-b136a77249e5.jpg)

**Comment by mariushosting** [comment]
![proton-mail-logo-31D8CDC79E-seeklogo com](https://user-images.githubusercontent.com/37554361/214727950-dc2a19b1-3f13-4f17-82d7-75abdaae26f7.png)
![proton-vpn-logo-A50452564D-seeklogo com](https://user-images.githubusercontent.com/37554361/214727955-7b082ed7-90aa-4016-bf04-062fa5d946dc.png)
![proton-calendar-logo-B77CBC60BC-seeklogo com](https://user-images.githubusercontent.com/37554361/214727958-d694d548-530d-4660-809e-01e981f36f2c.png)
![proton-drive-logo-9763A975ED-seeklogo com](https://user-images.githubusercontent.com/37554361/214727959-f3d1640c-badb-44ec-8043-21934ab7a0aa.png)
