### ISSUE TITLE
⚡ — png loads, svg with the same way wont load

### ISSUE THREAD

**Issue by IIIdefconIII** [walkxcode/dashboard-icons#251]
### Type

Documentation change

### Info

png files are loaded lik github:
png works fine, but svg doesnt load.

    - Homepage Github:
        icon:  github-light.png
        href: https://github.com/benphelps/homepage

_No response_

**Comment by walkxcode** [comment]
Hey, this is an issue on homepage's end. Please make an issue request there, by using [this link](https://github.com/benphelps/homepage/issues/new?assignees=&labels=bug&template=bug_report.yml&title=%5BBug%5D+)
