### ISSUE TITLE
[Icon Request]: Changedetection.io

### ISSUE THREAD

**Issue by agrider** [walkxcode/dashboard-icons#27]
**What is the name of the icon?**
changedetection.io

**What is the website/page of the icon?**
https://github.com/dgtlmoon/changedetection.io

**Upload the icon here: [Optional]**
I can't locate a .png or .svg, but here is the link to the favicon .ico. https://raw.githubusercontent.com/dgtlmoon/changedetection.io/master/changedetectionio/static/images/favicon.ico

**Comment by walkxcode** [comment]
Hello, I've added all your requested icons!

**Comment by agrider** [comment]
Awesome, thanks so much! One quick thing, I noticed that there's a spelling error in the filename for `changedetection-io.png` (currently `changedetection-io.png`)
