### ISSUE TITLE
Icon request for Wger

### ISSUE THREAD

**Issue by goaliedude3919** [walkxcode/dashboard-icons#288]
### Type

Icon request

### Info

https://raw.githubusercontent.com/wger-project/wger/master/wger/core/static/images/logos/logo.png

### Icon(s)

![wger](https://user-images.githubusercontent.com/77366789/221762454-e4faafb2-57ea-4b0b-b63a-b0c301fcf8cf.png)

**Comment by walkxcode** [comment]
All issues are temporarily on hold. Please refer to #316 for more info.

**Comment by walkxcode** [comment]
This icon is already in the repo.
