### ISSUE TITLE
Flame and B&W logos

### ISSUE THREAD

**Issue by adrianmihalko** [walkxcode/dashboard-icons#293]
### Type

Icon request

### Info

Hi,

Thanks for this great project, I just have a little feature request. I am using Flame and it is using black and white logos:

<img width="224" alt="Screenshot 2023-03-01 at 18 30 59" src="https://user-images.githubusercontent.com/733361/222217129-40cbb6ad-dcbe-4cc7-a1bb-54c7c97ddb14.png">

It would be great to have all logos available in black and white version too.

**Comment by walkxcode** [comment]
All issues are temporarily on hold. Please refer to #316 for more info.

**Comment by adrianmihalko** [comment]
Awesome news. 👍👍👍
