### ISSUE TITLE
[Enhancement]: Organizr

### ISSUE THREAD

**Issue by mcrutherford** [WalkxCode/dashboard-icons#3]
**What do you want to enhance?**
The organizr icon

**What is the enhancement?**
Icon with only the logo, no text
![organizr](https://user-images.githubusercontent.com/23453492/133096876-d22425f9-2706-4d36-8ac3-ee2b8268e2ca.png)

**Additional info: [Optional]**

**Comment by WalkxCode** [comment]
Thanks, I'll update it!

**Comment by WalkxCode** [comment]
The icon has been added!
