### ISSUE TITLE
Pairdrop icon request

### ISSUE THREAD

**Issue by trinsic** [walkxcode/dashboard-icons#317]
### Type

Icon request

### Info

Pairdrop: https://github.com/schlagmichdoch/PairDrop
Icon: https://raw.githubusercontent.com/schlagmichdoch/PairDrop/master/public/images/android-chrome-512x512.png

### Icon(s)

![android-chrome-512x512](https://user-images.githubusercontent.com/4532152/223979310-e007fb63-4493-497f-968f-60a89d2b77b6.png)

**Comment by tmeuze** [comment]
@trinsic while you wait, you may use the very similar icon for [Snapdrop](https://github.com/walkxcode/dashboard-icons/blob/main/png/snapdrop.png)

**Comment by trinsic** [comment]
Similar is an understatement!

**Comment by tmeuze** [comment]
Hey @trinsic - I think this is worthy of being reopened, imo. It's a quality submission, it meets the new standards, and it's ever-so-slightly distinguished. Please consider reopening.
