### ISSUE TITLE
[ICON REQUEST] Web Whisper

### ISSUE THREAD

**Issue by JohnDoe-dev-spec** [walkxcode/dashboard-icons#321]
### Type

Icon request

### Info

Icon for Web Whisper project. Uploaded below.

Thank you.

### Icon(s)

![webwhisper](https://user-images.githubusercontent.com/57029587/224576320-7839d24e-8760-4323-88bc-fbb18f079ff5.png)

**Comment by walkxcode** [comment]
Hey, this icon has been added in the `new-standards` branch and will be merged once it is done!

https://github.com/walkxcode/dashboard-icons/blob/new-standards/png/web-whisper
