### ISSUE TITLE
⚡ — Fix - changedetectionio

### ISSUE THREAD

**Issue by tmeuze** [walkxcode/dashboard-icons#324]
### Type

Icon enhancement

### Info

The icon for [ChangeDetection.io](https://github.com/walkxcode/dashboard-icons/blob/main/png/changedetectionio.png) is that of GitHub. The correct icon is shown below. 

Thank you. 

### Icon(s)

![changedetectionio](https://user-images.githubusercontent.com/9298659/225382400-50bdc41a-499a-4b20-9c0f-f8389a8b7ea1.svg)
![changedetectionio](https://user-images.githubusercontent.com/9298659/225382912-7b354345-e88f-4f26-8e18-e894801eeff4.png)

**Comment by walkxcode** [comment]
Icon has been fixed in the new branch. Will be merged soon!

https://github.com/walkxcode/dashboard-icons/blob/new-standards/png/changedetection-io

**Comment by tmeuze** [comment]
You are the best!

**Comment by tmeuze** [comment]
Hey @walkxcode! I don't see an entry for this icon file anymore, after the merge. Am I being impatient? Just wanted to check. 

Thanks for everything!

**Comment by walkxcode** [comment]
It's there on my end! Should be called changedetection-io.

**Comment by tmeuze** [comment]
So sorry - I see the [png](https://github.com/walkxcode/dashboard-icons/blob/main/png/changedetection-io.png) now. Search and Dashy cache just had me all messed up.
