### ISSUE TITLE
Omada icon fix

### ISSUE THREAD

**Issue by MAMedici** [walkxcode/dashboard-icons#325]
### Type

Icon enhancement

### Info

The "Omada" icon has unnecessary white space on either side, causing the icon to be scaled-down when displayed in a standard square icon format.  A properly square-cropped icon is attached.

### Icon(s)

![omada](https://user-images.githubusercontent.com/121360684/225483828-ad843289-6155-4998-b442-94400293fab4.png)

**Comment by nomandera** [comment]
https://github.com/walkxcode/dashboard-icons/pull/297

**Comment by walkxcode** [comment]
Icon has been fixed in the new branch. Will be merged soon!

https://github.com/walkxcode/dashboard-icons/blob/new-standards/png/omada.png
https://github.com/walkxcode/dashboard-icons/blob/new-standards/svg/omada.svg
