### ISSUE TITLE
[Icon Request]: WorkAdventure

### ISSUE THREAD

**Issue by deffcolony** [walkxcode/dashboard-icons#33]
**What is the name of the icon?**
WorkAdventure

**What is the website/page of the icon?**
https://workadventu.re

**Upload the icon here: [Optional]**
Upload the icon, MUST be `PNG` or `SVG`.

**Comment**
The logo looks burned into the text logo you should cut out the square coffee mug and use that as logo

**Comment by walkxcode** [comment]
Added the icon! Thanks for the suggestion.
