### ISSUE TITLE
AT&T Logo

### ISSUE THREAD

**Issue by generationsbroadcasting** [walkxcode/dashboard-icons#334]
### Type

Icon request

### Info

Logo for AT&T, largest ISP and cell network in US.

### Icon(s)

![att-logo-1](https://user-images.githubusercontent.com/125162284/229448521-3bc6c57a-bd0d-45a3-9eb9-5a727b8dab2a.png)

**Comment by walkxcode** [comment]
Hey, this icon has been added in the `new-standards` branch and will be merged once it is done!

https://github.com/walkxcode/dashboard-icons/blob/new-standards/png/at-t.png
https://github.com/walkxcode/dashboard-icons/blob/new-standards/svg/at-t.svg
