### ISSUE TITLE
⚡ Cryptomator

### ISSUE THREAD

**Issue by schancksb** [walkxcode/dashboard-icons#335]
### Type

Icon request

### Info

https://cryptomator.org/ 

> Cryptomator is a simple tool for digital self-defense. It allows you to protect your cloud data by yourself and independently.

Logo downloaded from https://cryptomator.org/presskit/cryptomator-logo.png

### Icon(s)

![cryptomator-logo](https://user-images.githubusercontent.com/47981550/229631501-e9c07836-cc58-4b0b-9fdf-75b1f54c6ec4.png)

**Comment by walkxcode** [comment]
Hey, this icon has been added in the `new-standards` branch and will be merged once it is done!

https://github.com/walkxcode/dashboard-icons/blob/new-standards/png/cryptomator.png
https://github.com/walkxcode/dashboard-icons/blob/new-standards/svg/cryptomator.svg
