### ISSUE TITLE
Etesync/Etebase

### ISSUE THREAD

**Issue by BadCo-NZ** [walkxcode/dashboard-icons#337]
### Type

Icon request

### Info

https://github.com/etesync/server
https://github.com/etesync/server/blob/master/icon.svg

### Icon(s)

![image](https://user-images.githubusercontent.com/50016048/230356510-94be24fa-0204-492c-901f-7360d19ee441.png)

**Comment by walkxcode** [comment]
Hey, this icon has been added in the `new-standards` branch and will be merged once it is done!

https://github.com/walkxcode/dashboard-icons/blob/new-standards/png/etesync.png
https://github.com/walkxcode/dashboard-icons/blob/new-standards/svg/etesync.svg

**Comment by BadCo-NZ** [comment]
> Hey, this icon has been added in the `new-standards` branch and will be merged once it is done!
> 
> https://github.com/walkxcode/dashboard-icons/blob/new-standards/png/etesync.png https://github.com/walkxcode/dashboard-icons/blob/new-standards/svg/etesync.svg

Thanks!
