### ISSUE TITLE
Mumble

### ISSUE THREAD

**Issue by BadCo-NZ** [walkxcode/dashboard-icons#338]
### Type

Icon request

### Info

https://github.com/mumble-voip/mumble
https://github.com/mumble-voip/mumble/blob/master/icons/mumble.svg

### Icon(s)

![image](https://user-images.githubusercontent.com/50016048/230356785-32da5edb-0495-41bf-bef5-3f003cde5b58.png)

**Comment by walkxcode** [comment]
Hey, this icon has been added in the `new-standards` branch and will be merged once it is done!

https://github.com/walkxcode/dashboard-icons/blob/new-standards/png/mumble.png
https://github.com/walkxcode/dashboard-icons/blob/new-standards/svg/mumble.svg

**Comment by BadCo-NZ** [comment]
> Hey, this icon has been added in the `new-standards` branch and will be merged once it is done!
> 
> https://github.com/walkxcode/dashboard-icons/blob/new-standards/png/mumble.png https://github.com/walkxcode/dashboard-icons/blob/new-standards/svg/mumble.svg

Thanks!
