### ISSUE TITLE
IT-Tools

### ISSUE THREAD

**Issue by BadCo-NZ** [walkxcode/dashboard-icons#339]
### Type

Icon request

### Info

https://github.com/CorentinTh/it-tools
https://github.com/CorentinTh/it-tools/blob/main/.github/logo.png

### Icon(s)

![image](https://user-images.githubusercontent.com/50016048/230374118-8f48300d-1344-47d5-9d22-9e00d94e4264.png)

**Comment by BadCo-NZ** [comment]
> Would be worth checking out the logo images in the below location which come in a square aspect ratio and an SVG available https://github.com/CorentinTh/it-tools/tree/main/public

Thanks @bgh-github good spotting!

**Comment by walkxcode** [comment]
Hey, this icon has been added in the `new-standards` branch and will be merged once it is done!

https://github.com/walkxcode/dashboard-icons/blob/new-standards/png/it-tools-light.png
https://github.com/walkxcode/dashboard-icons/blob/new-standards/png/it-tools.png
https://github.com/walkxcode/dashboard-icons/blob/new-standards/svg/it-tools.svg

**Comment by BadCo-NZ** [comment]
> Hey, this icon has been added in the `new-standards` branch and will be merged once it is done!
> 
> https://github.com/walkxcode/dashboard-icons/blob/new-standards/png/it-tools-light.png https://github.com/walkxcode/dashboard-icons/blob/new-standards/png/it-tools.png https://github.com/walkxcode/dashboard-icons/blob/new-standards/svg/it-tools.svg

Thanks!
