### ISSUE TITLE
Add icon for Minimserver

### ISSUE THREAD

**Issue by elisimpson** [walkxcode/dashboard-icons#340]
### Type

Icon request

### Info

Including png icon extracted from the official MacOS install package.

Official website:
https://minimserver.com

### Icon(s)

![minimserver_128x128x32](https://user-images.githubusercontent.com/13845022/230480211-9ad1e548-3e59-4973-aa27-8dd19a1bd6c3.png)

**Comment by walkxcode** [comment]
Hey, this icon has been added in the `new-standards` branch and will be merged once it is done!

https://github.com/walkxcode/dashboard-icons/blob/new-standards/png/minimserver.png
