### ISSUE TITLE
⚡ — Add SFTPgo icon

### ISSUE THREAD

**Issue by zoharxero** [walkxcode/dashboard-icons#347]
### Type

Icon request

### Info

Icon here: 

https://d7umqicpi7263.cloudfront.net/img/product/b847d5b1-151d-48b9-8582-ca2efd45adfb/ef815ed6-90c4-4054-afeb-5eaecbe4e011

**Comment by walkxcode** [comment]
Hey, this icon has been added in the `new-standards` branch and will be merged once it is done!

https://github.com/walkxcode/dashboard-icons/blob/new-standards/png/sftpgo.png
