### ISSUE TITLE
⚡ — Add Gonic icon

### ISSUE THREAD

**Issue by zoharxero** [walkxcode/dashboard-icons#348]
### Type

Icon request

### Info

Add Gonic icon

### Icon(s)

![gonic](https://user-images.githubusercontent.com/15709414/230813151-53d41c0c-f15a-41ea-a89d-5861418d569b.png)

**Comment by walkxcode** [comment]
Hey, this icon has been added in the `new-standards` branch and will be merged once it is done!

https://github.com/walkxcode/dashboard-icons/blob/new-standards/png/gonic.png
