### ISSUE TITLE
⚡ — Add substreamer icon

### ISSUE THREAD

**Issue by zoharxero** [walkxcode/dashboard-icons#349]
### Type

None

### Info

Add Substreamer icon

### Icon(s)

![icon_substreamer](https://user-images.githubusercontent.com/15709414/230813536-c7ead2dc-e8e8-4f12-a947-bfed887f0d01.png)

**Comment by walkxcode** [comment]
Hey, could you link me to where you found this icon?

**Comment by mspray** [comment]
I just lost the icons for : 
- Radical
- Authentik
- Nginx proxy Manager
- Radarr (although there are still those for Sonarr and even Readarr)
- Docker 

the last three are really common so just why ?

**Comment by zoharxero** [comment]
> 

It was taken from the assets folder of the container.

https://hub.docker.com/r/ghenry22/substreamer

**Comment by walkxcode** [comment]
Does there happen to be an SVG version in that folder as well? If so, could you send it too?
