### ISSUE TITLE
⚡ — *Add Mullvad icon*

### ISSUE THREAD

**Issue by Jerdle** [walkxcode/dashboard-icons#350]
### Type

Icon request

### Info

Mullvad.. uploaded best one I could find

### Icon(s)

![Screenshot 2023-04-10 at 10 35 14 AM](https://user-images.githubusercontent.com/10408060/230923594-dca99e07-7b84-4a0d-a3f6-e27d396d7549.png)

**Comment by walkxcode** [comment]
Hey, this icon has been added in the `new-standards` branch and will be merged once it is done!

https://github.com/walkxcode/dashboard-icons/blob/new-standards/png/mullvad.png
https://github.com/walkxcode/dashboard-icons/blob/new-standards/svg/mullvad.svg
