### ISSUE TITLE
New logo Password Pusher

### ISSUE THREAD

**Issue by angeloschat** [walkxcode/dashboard-icons#351]
### Type

None

### Info

https://github.com/pglombardo/PasswordPusher

### Icon(s)

![logo-transparent-sm-bare-93087ef5826f108beca4451b8b136578762c767556877f2736ff55469b99cf75](https://user-images.githubusercontent.com/38050638/230939845-5ebea764-c32d-45c7-81cb-344a9e8804c0.png)

**Comment by walkxcode** [comment]
Hey, this icon has been added in the `new-standards` branch and will be merged once it is done!

https://github.com/walkxcode/dashboard-icons/blob/new-standards/png/passwordpusher.png
