### ISSUE TITLE
Borg (BorgBackup)

### ISSUE THREAD

**Issue by tmeuze** [walkxcode/dashboard-icons#360]
### Icon Name

borg.svg
borg.png

### Icon(s)

SVG:
![borg.svg](https://user-images.githubusercontent.com/9298659/232169600-03e72978-4078-4803-aa94-332a329b6616.svg)

PNG:
![borg.png](https://user-images.githubusercontent.com/9298659/232169997-8b0b8001-fa5e-489a-a2ee-9a8017489850.png)

**Comment by walkxcode** [comment]
Does this logo have a black background by design, or can it be removed?

**Comment by tmeuze** [comment]
It is by design - but I can work on removing it if that'd be valid.

**Comment by tmeuze** [comment]
Here's a submission without background:

![borg](https://user-images.githubusercontent.com/9298659/232238364-bd72565b-671d-408c-8a19-aea7083c3401.svg)

![borg](https://user-images.githubusercontent.com/9298659/232238365-5f95b725-6fb8-4895-8496-6a87517ef6c1.png)

And the original, which I failed to scale to 512px height:

![borg](https://user-images.githubusercontent.com/9298659/232238394-5c2e1adb-4301-4f05-b9d3-5f4f45ffb510.svg)

![borg](https://user-images.githubusercontent.com/9298659/232238396-a48d23af-3e92-427a-a57c-8dd879965ccc.png)
