### ISSUE TITLE
Memos changed their icon

### ISSUE THREAD

**Issue by tiritibambix** [walkxcode/dashboard-icons#380]
See on their website: https://usememos.com/

Here is the icon: https://usememos.com/logo.webp

Cheers

**Comment by walkxcode** [comment]
Do you know if there is an SVG available for this?

**Comment by tiritibambix** [comment]
Sorry, I have no idea. You could ask the dev.

I tried an online convertion on some random website and got [this](https://clip.steph.click/-CCCc7cLkuz).
