### ISSUE TITLE
[Icon Request]: Cloudflare

### ISSUE THREAD

**Issue by mcrutherford** [WalkxCode/dashboard-icons#4]
**What is the name of the icon?**
Cloudflare

**What is the website/page of the icon?**
https://www.cloudflare.com/

**Upload the icon here: [Optional]**
![cloudflare](https://user-images.githubusercontent.com/23453492/133097025-3345acd6-64eb-443a-a25d-e78320bf83bc.png)

**Comment by WalkxCode** [comment]
Adding rn

**Comment by WalkxCode** [comment]
The icon has been added!
