### ISSUE TITLE
A TP-Link icon for TP-Link Wifi APs

### ISSUE THREAD

**Issue by jmlc11** [walkxcode/dashboard-icons#404]
### Icon Name

TP-Link.png

### Icon(s)

![TP-Link](https://user-images.githubusercontent.com/6006781/236543884-158ab698-0233-40fc-9ee5-edde99fcef5e.svg)
![TP-Link](https://user-images.githubusercontent.com/6006781/236544231-2da206b8-9dde-43ff-a9f0-11a675341487.png)

**Comment by walkxcode** [comment]
This icon is already in the repo. https://github.com/walkxcode/dashboard-icons/blob/main/png/tp-link.png

**Comment by jmlc11** [comment]
It was not working and when i ctrl + f tp-link i got no results here. Sorry!
