### ISSUE TITLE
New logo for Caddy

### ISSUE THREAD

**Issue by umfk** [walkxcode/dashboard-icons#419]
### Icon Name

caddy

### Icon(s)

An SVG that only has to be stripped of the wordmark can be found here:

https://en.wikipedia.org/wiki/File:Caddy_2_lock_icon_and_wordmark_logo.svg

**Comment by walkxcode** [comment]
Since the new logo doesn't have a squared version, I will be unable to update it until they provide one.

**Comment by umfk** [comment]
I just cropped these square logos from the linked svg, is that alright?

![caddy](https://github.com/walkxcode/dashboard-icons/assets/17507776/f6983ffc-5407-4fa8-b733-cc3a525bfdc4)
![caddy](https://github.com/walkxcode/dashboard-icons/assets/17507776/89644361-b944-44e8-83bf-58a77929b3b6)
