### ISSUE TITLE
⚡ — Add IMMICH logo

### ISSUE THREAD

**Issue by darrylgibbs** [walkxcode/Dashboard-Icons#42]
### Info

Immich photos backup server

### Icon(s)

![immich](https://user-images.githubusercontent.com/9167471/189968592-d281b1a3-173a-4bae-8061-9176190a5509.png)

**Comment by walkxcode** [comment]
Hey, would you happen to have a transparent version of this image?

**Comment by walkxcode** [comment]
Done in #43
