### ISSUE TITLE
Nginx Proxy Manager icon removed?

### ISSUE THREAD

**Issue by PicoPlanetDev** [walkxcode/dashboard-icons#422]
### Icon Name

# Nginx Proxy Manager

I have used the `nginxproxymanager.png` icon in Homepage for my homelab server for a few months, and it recently disappeared. It doesn't seem to be available here on Dashboard Icons anymore. This is more of a request to reinstate it than anything else.

### Icon(s)

![logo](https://github.com/walkxcode/dashboard-icons/assets/50522829/f50b383e-2e82-4d95-b8bd-4b82082c567c)

**Comment by walkxcode** [comment]
This icon was renamed. See https://github.com/walkxcode/dashboard-icons/blob/main/png/nginx-proxy-manager.png
