### ISSUE TITLE
Add Odoo

### ISSUE THREAD

**Issue by andreapx** [walkxcode/dashboard-icons#439]
### Icon Name

hl-odoo

### Icon(s)

![odoo_logo](https://github.com/walkxcode/dashboard-icons/assets/13846728/28dcd8c0-b252-4c8a-9f4f-9f2ebad21811)
![odoo_logo](https://github.com/walkxcode/dashboard-icons/assets/13846728/026ea57d-3308-48c0-ad10-30b355bf74e4)

**Comment by walkxcode** [comment]
I'm currently traveling and only have access to the GitHub web-ui. I will add this into the project when I am able to do so.

**Comment by andreapx** [comment]
Thanks!
