### ISSUE TITLE
⚡ — Notifiarr

### ISSUE THREAD

**Issue by Droppisalt** [walkxcode/Dashboard-Icons#44]
### Type

Icon request

### Info

Would like the icon for Notifiarr:
https://github.com/Notifiarr/notifiarr

**Comment by walkxcode** [comment]
This is the best icon I could find, is this good for you?

![notifiarr](https://user-images.githubusercontent.com/71191962/190778392-95625edc-062f-4415-934d-d968fef31a52.png)

**Comment by Droppisalt** [comment]
> This is the best icon I could find, is this good for you?
> 
> ![notifiarr](https://user-images.githubusercontent.com/71191962/190778392-95625edc-062f-4415-934d-d968fef31a52.png)
> 

Definitely! Just glad to have it added at all :D
