### ISSUE TITLE
Please add diyhue

### ISSUE THREAD

**Issue by BoKKeR** [walkxcode/dashboard-icons#452]
### Icon Name

diyhue

### Icon(s)

![5594370](https://github.com/walkxcode/dashboard-icons/assets/2664857/160088e2-1167-487a-b15b-a6ff0dbf109c)

**Comment by walkxcode** [comment]
Hi, would you happen to have a transparent version of this logo?

**Comment by BoKKeR** [comment]
I got this from removebg 
![258642073-160088e2-1167-487a-b15b-a6ff0dbf109c-removebg-preview](https://github.com/walkxcode/dashboard-icons/assets/2664857/fa69aefb-0546-4a1d-9a90-bc466ab8d443)
