### ISSUE TITLE
Please Fix MinIO icon to be red

### ISSUE THREAD

**Issue by audiophonicz** [walkxcode/dashboard-icons#454]
### Icon Name

minio-bird

(per https://min.io/logo)

### Icon(s)

![minio-bird](https://github.com/walkxcode/dashboard-icons/assets/89954085/d8a87fb6-7fb1-4c9f-a70a-255ccc5fdd88)

**Comment by walkxcode** [comment]
Hello, I was unable to find any official SVG in red, so I have decided not to do this.

**Comment by audiophonicz** [comment]
Hello, thanks for your review. I was under the impression from the guidelines that an SVG was not required.  I can try to produce an SVG if need be. I have provided the link to the official logo downloads as well as the correctly sized PNG.

The official logo is red. The current black PNG is invisible with most dark modes. The official red would be much easier to see against dark modes. Please reconsider.

**Comment by walkxcode** [comment]
All icons have both a dark and light version available 🙂 If you would like to make a good SVG that would be very much appreciated.

**Comment by nomandera** [comment]
As an experiment I used the free online service https://png2svg.com/

I am no expert but I am very impressed.

Original taken from https://min.io/resources/img/logo/MINIO_Bird.png

with a very clean output (open in txt editor to see how clean this is). It is no perfect but given it is zero skill it surely has to be an option to document.

![MINIO_Bird](https://github.com/walkxcode/dashboard-icons/assets/1133344/fcd1186d-cb48-48ad-84b2-2d8941f50362)
