### ISSUE TITLE
Add Wiki.js

### ISSUE THREAD

**Issue by magicbret** [walkxcode/dashboard-icons#455]
### Icon Name

wiki-js

### Icon(s)

<img width="296" alt="wikijs" src="https://github.com/walkxcode/dashboard-icons/assets/7100026/50b0ca61-c4b2-4dac-a4fa-b7962f04e948">

**Comment by walkxcode** [comment]
Wiki.JS is already in the repo [here](https://github.com/walkxcode/dashboard-icons/blob/main/png/wikijs.png).
