### ISSUE TITLE
Please add "HiFiBerry"

### ISSUE THREAD

**Issue by EpicLPer** [walkxcode/dashboard-icons#460]
Icon Name: `hifiberry`

PNG: 
![hifiberry](https://github.com/walkxcode/dashboard-icons/assets/8442196/159b5292-b5db-4a27-b0f2-d62bddb9a8cc)

SVG: This is an alternative version of this icon, so I'm not sure how exactly to treat this. This is a direct link to the SVG file which needs some editing first.  
https://www.hifiberry.com/wp-content/themes/hifiberry/assets/images/hifiberry_logo.svg

**Comment by walkxcode** [comment]
Hi, I don't have a lot of time, and I'm just quickly scanning through PRs and issues, would you be able to edit the SVG? There should be plenty of online tools to do this.

**Comment by walkxcode** [comment]
@EpicLPer Reminder :)
