### ISSUE TITLE
Please add 'Nextcloud-Tasks'

### ISSUE THREAD

**Issue by stathiskef** [walkxcode/dashboard-icons#465]
### Icon Name

nextcloud-tasks

### Icon(s)

![nextcloud-tasks](https://github.com/walkxcode/dashboard-icons/assets/23315858/1c17e608-6c9a-4c40-a96c-5f3be396151c)
![nextcloud-tasks](https://github.com/walkxcode/dashboard-icons/assets/23315858/b5ab5904-ec9d-4ebe-8c30-7e45de96de9c)

**Comment by walkxcode** [comment]
Hi, I can't seem to find any page showing this as the real icon. Could you link me to it?

**Comment by walkxcode** [comment]
@stathiskef Reminder :)

**Comment by emhl** [comment]
#475 already added the nextcloud tasks icon. and it can be found [here](https://github.com/nextcloud/tasks/blob/master/img/favicon.svg)
