### ISSUE TITLE
Wazuh with white logo instead of transparent

### ISSUE THREAD

**Issue by treverehrfurth** [walkxcode/dashboard-icons#483]
### Icon Name

wazuh-white.png

### Icon(s)

![wazuh-white](https://github.com/walkxcode/dashboard-icons/assets/25590075/8063a96d-f9da-45c3-aed7-836b0bd8d82d)

**Comment by Pray4Tre** [comment]
Can this be added?

**Comment by walkxcode** [comment]
Hi, do you have an SVG available for this?

**Comment by Pray4Tre** [comment]
I do not but when I get home I can try and export as one possibly. Thank you

**Comment by Pray4Tre** [comment]
![wazuh-white](https://github.com/walkxcode/dashboard-icons/assets/25590075/70137d49-ea21-4408-9648-55596304f590)

**Comment by Pray4Tre** [comment]
There is the SVG.

I saw this was added to the commit but when will this reflect in the code?
I still only see the transparent version in there, not this one.

Thank you!

**Comment by walkxcode** [comment]
Hi, the SVG seems to be just an image embedded into the SVG. Is there an actual SVG available? I have only just now started working on this issue!
