### ISSUE TITLE
[Icon Request]: Etherpad

### ISSUE THREAD

**Issue by mcrutherford** [WalkxCode/dashboard-icons#5]
**What is the name of the icon?**
Etherpad

**What is the website/page of the icon?**
https://etherpad.org/

**Upload the icon here: [Optional]**
![etherpad](https://user-images.githubusercontent.com/23453492/133097161-f3d02ec7-0e06-4a19-afd0-070f4b94d410.png)

**Comment by WalkxCode** [comment]
Addin!

**Comment by WalkxCode** [comment]
The icon has been added!
