### ISSUE TITLE
Memos changed there branding again

### ISSUE THREAD

**Issue by hfabre** [walkxcode/dashboard-icons#504]
### Icon Name

memos

### Icon(s)

You can look at logos [on the new brand page](https://www.usememos.com/brand) and take files [on the github repo](https://github.com/usememos/dotcom/tree/main/public).

I would probably take [logo-rounded.png](https://github.com/usememos/dotcom/blob/main/public/logo-rounded.png) but that's a matter of taste I guess.

Here is the Svg version  converted with [this website](https://convertio.co)

![Svg version](https://github.com/walkxcode/dashboard-icons/assets/4941447/e71364db-a200-40f4-b16e-6fbaddb03170)

**Comment by walkxcode** [comment]
Hi, this has been added with PR #488
