### ISSUE TITLE
Add Octoprint

### ISSUE THREAD

**Issue by Yoanf26** [walkxcode/dashboard-icons#510]
### Icon Name

octoprint.png

### Icon(s)

![octoprint](https://github.com/walkxcode/dashboard-icons/assets/38152898/054fae6d-7b91-488d-af76-d57bbf0e29fc)

**Comment by walkxcode** [comment]
Hi, octoprint has been in the repo for a long time. https://github.com/walkxcode/dashboard-icons/blob/main/png/octoprint.png
