### ISSUE TITLE
Add Cockpit Linux

### ISSUE THREAD

**Issue by Yoanf26** [walkxcode/dashboard-icons#512]
### Icon Name

cockpit-linux.png

### Icon(s)

![cockpit-linux](https://github.com/walkxcode/dashboard-icons/assets/38152898/dd01f82a-31c1-44dd-87e5-738c514a759e)

**Comment by walkxcode** [comment]
Hi, this icon is already in the repo. https://github.com/walkxcode/dashboard-icons/blob/main/png/cockpit.png
