### ISSUE TITLE
Resizing of GitLab icon

### ISSUE THREAD

**Issue by bobbyl140** [walkxcode/dashboard-icons#574]
### Contribution Guidelines

- [X] I have read and agree to the [Contribution Guidelines](https://github.com/walkxcode/dashboard-icons/blob/main/CONTRIBUTING.md)

### Icon Name

This isn't a new icon, rather a request to change an existing one: the GitLab icon is smaller than all the others, with transparent pixels around the logo but with more padding than the others. Along with a bunch of the other icons on a dashboard it doesn't look great. Is resizing this icon to have fewer transparent pixels around it a possibility? Example of what I mean: 
<img width="242" alt="Screenshot 2024-01-18 at 11 10 08 AM" src="https://github.com/walkxcode/dashboard-icons/assets/61990607/bc3c04af-c47f-474a-809f-06f790c9203f">
(Every icon except GitLab is the same size as FreePBX.)

### Icon(s)

N/A

**Comment by walkxcode** [comment]
Hi, this icon came from the gitlab presskit, but I will modify it! Thanks for noticing it

**Comment by walkxcode** [comment]
Sorry, accidentally mentioned the wrong issue. Fixed! https://github.com/walkxcode/dashboard-icons/commit/8b8ae0385638662d16e413ef216d393fb0f6c853
