### ISSUE TITLE
Add Doku

### ISSUE THREAD

**Issue by ameer1234567890** [walkxcode/dashboard-icons#581]
### Contribution Guidelines

- [X] I have read and agree to the [Contribution Guidelines](https://github.com/walkxcode/dashboard-icons/blob/main/CONTRIBUTING.md)

### Icon Name

Doku
https://github.com/amerkurev/doku

### Icon(s)

![favicon 1](https://github.com/walkxcode/dashboard-icons/assets/160157/a48cfce2-4287-44b2-ba20-e6bf36407ef2)

**Comment by walkxcode** [comment]
Hi, Doku doesn't seem to have an official icon. Where did you get this one?

**Comment by ameer1234567890** [comment]
https://raw.githubusercontent.com/amerkurev/doku/master/web/doku/public/favicon.ico

**Comment by walkxcode** [comment]
Closing because there is no icon available with a reasonable resolution.
