### ISSUE TITLE
Update Ntfy icons

### ISSUE THREAD

**Issue by Roundaround** [walkxcode/dashboard-icons#598]
I was going to make a pull request for this but I'm not sure how you want to go about it. Right now you have ntfy.png, ntfy-light.png, and ntfy.svg, but they're all outline style. The real icon has a gradient fill and static border color (linked below). I could of course just replace the ntfy.png and ntfy.svg, but then ntfy-light.png seems out of place. What is the best way forward?

Side question: do you prefer the issue form or direct pull requests for contributing new icons?

SVG:
![ntfy](https://github.com/walkxcode/dashboard-icons/assets/4167222/e465911d-ed48-4c59-9424-e60ac7e1db90)

PNG:
![pwa-512x512](https://github.com/walkxcode/dashboard-icons/assets/4167222/14dd8aa4-ad1f-4c37-a49c-21933c716e38)

**Comment by walkxcode** [comment]
Hey, I prefer direct PRs! For now I've created a dark version myself using deeditor.
