### ISSUE TITLE
[Icon Request]: Petio

### ISSUE THREAD

**Issue by mcrutherford** [WalkxCode/dashboard-icons#6]
**What is the name of the icon?**
Petio

**What is the website/page of the icon?**
https://petio.tv/

**Upload the icon here: [Optional]**
![petio](https://user-images.githubusercontent.com/23453492/133097910-f2a46bb9-d2d8-469d-9823-e637fb71d413.png)

**Comment by WalkxCode** [comment]
adding!

**Comment by WalkxCode** [comment]
The icon has been added!
