### ISSUE TITLE
Update Immich to New logo

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [walkxcode/dashboard-icons#634]
### Contribution Guidelines

- [X] I have read and agree to the [Contribution Guidelines](https://github.com/walkxcode/dashboard-icons/blob/main/CONTRIBUTING.md)

### Icon Name

Immich has a new logo which has rolled out today in version 1.99 and is detailed [here](https://github.com/immich-app/immich/discussions/6318)
Please add the new logo/update the current logo.

**Comment by walkxcode** [comment]
Has been updated in https://github.com/walkxcode/dashboard-icons/commit/7207d4f09479c18a56ac8c2b0340541b44d7b711
