### ISSUE TITLE
Directus icon

### ISSUE THREAD

**Issue by marcin212** [walkxcode/dashboard-icons#645]
### Contribution Guidelines

- [X] I have read and agree to the [Contribution Guidelines](https://github.com/walkxcode/dashboard-icons/blob/main/CONTRIBUTING.md)

### Icon Name

directus

### Icon(s)
PNG:
<img width="256" alt="directus" src="https://github.com/walkxcode/dashboard-icons/assets/3790635/5fec62e6-5d9c-43e2-9550-946509c5b7bb">

SVG:
![directus](https://github.com/walkxcode/dashboard-icons/assets/3790635/39c85cc6-68fd-4a45-a7b7-bf779d07bed7)

**Comment by walkxcode** [comment]
Directus is already in the repo.
