### ISSUE TITLE
Add light version of Tailscale 

### ISSUE THREAD

**Issue by ilude** [walkxcode/dashboard-icons#658]
### Contribution Guidelines

- [X] I have read and agree to the [Contribution Guidelines](https://github.com/walkxcode/dashboard-icons/blob/main/CONTRIBUTING.md)

### Icon Name

tailscale-light.svg

### Icon(s)

![tailscale-white](https://github.com/walkxcode/dashboard-icons/assets/219478/b04807e7-9f5b-490b-9d34-24ed3bec6596)

**Comment by walkxcode** [comment]
https://github.com/walkxcode/dashboard-icons/blob/main/png/tailscale-light.png
