### ISSUE TITLE
Add Coolify icon

### ISSUE THREAD

**Issue by zoharxero** [walkxcode/dashboard-icons#662]
### Contribution Guidelines

- [X] I have read and agree to the [Contribution Guidelines](https://github.com/walkxcode/dashboard-icons/blob/main/CONTRIBUTING.md)

### Icon Name

Coolify https://coolify.io/

### Icon(s)

![image](https://github.com/walkxcode/dashboard-icons/assets/15709414/8c799967-f66f-4d53-8543-defa2cf49db8)

**Comment by walkxcode** [comment]
https://github.com/walkxcode/dashboard-icons/pull/684
