### ISSUE TITLE
Jellyseerr update icon

### ISSUE THREAD

**Issue by ySteini** [walkxcode/dashboard-icons#668]
### Contribution Guidelines

- [x] I have read and agree to the [Contribution Guidelines](https://github.com/walkxcode/dashboard-icons/blob/main/CONTRIBUTING.md)

### Icon Name

jellyseerr

### Icon(s)

![jellyseer](https://github.com/walkxcode/dashboard-icons/assets/74825963/f6521d79-a368-4809-8b0d-b1a9a910ffeb)

**Comment by walkxcode** [comment]
https://github.com/walkxcode/dashboard-icons/pull/710
