### ISSUE TITLE
Net Alert X

### ISSUE THREAD

**Issue by stanthewizzard** [walkxcode/dashboard-icons#670]
### Contribution Guidelines

- [X] I have read and agree to the [Contribution Guidelines](https://github.com/walkxcode/dashboard-icons/blob/main/CONTRIBUTING.md)

### Icon Name

Net Alert X

**Comment by stanthewizzard** [comment]
https://github.com/jokob-sk/NetAlertX

**Comment by walkxcode** [comment]
Duplicate of https://github.com/walkxcode/dashboard-icons/issues/667
