### ISSUE TITLE
Add Icon - Kestra

### ISSUE THREAD

**Issue by mdw466** [walkxcode/dashboard-icons#678]
### Contribution Guidelines

- [X] I have read and agree to the [Contribution Guidelines](https://github.com/walkxcode/dashboard-icons/blob/main/CONTRIBUTING.md)

### Icon Name

Kestra

https://kestra.io/

### Icon(s)

![kestra](https://github.com/walkxcode/dashboard-icons/assets/112593609/d46fe504-5f27-49b5-925d-c77e825b8e56)

**Comment by walkxcode** [comment]
https://github.com/walkxcode/dashboard-icons/pull/661
