### ISSUE TITLE
Add Gemini icon

### ISSUE THREAD

**Issue by BillStewRod** [walkxcode/dashboard-icons#680]
### Contribution Guidelines

- [X] I have read and agree to the [Contribution Guidelines](https://github.com/walkxcode/dashboard-icons/blob/main/CONTRIBUTING.md)

### Icon Name

google-gemini-icon

### Icon(s)

![google-gemini-icon](https://github.com/walkxcode/dashboard-icons/assets/95992804/a17abaf6-99ce-40db-a54e-7d9d80fd3453)
![google-gemini-icon](https://github.com/walkxcode/dashboard-icons/assets/95992804/62cff81a-05f1-408d-ab90-c47380963e90)

**Comment by walkxcode** [comment]
https://github.com/walkxcode/dashboard-icons/pull/683
