### ISSUE TITLE
Add Copilot Icon

### ISSUE THREAD

**Issue by BillStewRod** [walkxcode/dashboard-icons#681]
### Contribution Guidelines

- [X] I have read and agree to the [Contribution Guidelines](https://github.com/walkxcode/dashboard-icons/blob/main/CONTRIBUTING.md)

### Icon Name

copilot-icon

### Icon(s)

![copilot-icon](https://github.com/walkxcode/dashboard-icons/assets/95992804/cb9d1046-36e6-4956-ba79-7efa4153ca80)
![copilot-icon](https://github.com/walkxcode/dashboard-icons/assets/95992804/319ca68d-2683-4ec4-8e5a-499dd6d68a81)

**Comment by walkxcode** [comment]
https://github.com/walkxcode/dashboard-icons/pull/683
