### ISSUE TITLE
ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by Drynael** [walkxcode/dashboard-icons#682]
Hello,

since today i get this error and not a single Icon is loaded:

![image](https://github.com/walkxcode/dashboard-icons/assets/15029013/806458e6-cd70-4860-9708-661f9a997e6f)

![image](https://github.com/walkxcode/dashboard-icons/assets/15029013/7c80a1b0-32a0-4036-9b7b-498c9a345a8c)

If i click "Continue to cdn.jsdelivr.net (unsafe) i get on a Cloudflare Error Page:

> 403 Forbidden
> cloudflare

Greetings from Germany

**Comment by marvintnk** [comment]
Same here for me - Germany.

**Comment by walkxcode** [comment]
Hi, this is most likely an error with jsdelivr. Please reach out to them directly.
