### ISSUE TITLE
Add icon wastebin

### ISSUE THREAD

**Issue by haruzept** [walkxcode/dashboard-icons#688]
### Contribution Guidelines

- [X] I have read and agree to the [Contribution Guidelines](https://github.com/walkxcode/dashboard-icons/blob/main/CONTRIBUTING.md)

### Icon Name

wastebin

### Icon(s)

https://raw.githubusercontent.com/matze/wastebin/master/assets/favicon.png

**Comment by walkxcode** [comment]
Wastebin doesn't seem to have any acceptable quality logo. Feel free to re-open if you can provide one.
