### ISSUE TITLE
Add Restreamer @Datahei

### ISSUE THREAD

**Issue by ramazansancar** [walkxcode/dashboard-icons#691]
### Contribution Guidelines

- [X] I have read and agree to the [Contribution Guidelines](https://github.com/walkxcode/dashboard-icons/blob/main/CONTRIBUTING.md)

### Icon Name

restreamer-datahei

### Icon(s)

SVG: ![https://raw.githubusercontent.com/datarhei/restreamer-ui/main/src/misc/Logo/images/rs-logo.svg](https://raw.githubusercontent.com/datarhei/restreamer-ui/main/src/misc/Logo/images/rs-logo.svg)
https://raw.githubusercontent.com/datarhei/restreamer-ui/main/src/misc/Logo/images/rs-logo.svg

PNG: ![https://github.com/walkxcode/dashboard-icons/assets/8878055/ebcef019-8bd5-4734-afa2-cfaa8da6204f](https://github.com/walkxcode/dashboard-icons/assets/8878055/ebcef019-8bd5-4734-afa2-cfaa8da6204f)
https://github.com/walkxcode/dashboard-icons/assets/8878055/ebcef019-8bd5-4734-afa2-cfaa8da6204f

**Comment by walkxcode** [comment]
I can't find any reasonably high quality icon for this as the SVG is just an image. Feel free to re-open if you can provide one.

**Comment by ramazansancar** [comment]
When I checked, the part in the picture is the fuel-spraying part of the rocket at the bottom left.

I don't think there would be much of a difference if we took it out of the picture, should we try it that way? @walkxcode 


https://github.com/datarhei/restreamer/blob/2.x/ui-root/index_icon.svg
