### ISSUE TITLE
Add shelly-alt icon

### ISSUE THREAD

**Issue by tutomun** [walkxcode/dashboard-icons#695]
### Contribution Guidelines

- [X] I have read and agree to the [Contribution Guidelines](https://github.com/walkxcode/dashboard-icons/blob/main/CONTRIBUTING.md)

### Icon Name

shelly-alt.png

### Icon(s)

![shelly-alt](https://github.com/walkxcode/dashboard-icons/assets/33230248/40225c59-0091-48e5-a6d1-2e96bf12caf8)

Note: this is an upscaled version of the original media asset provided by Shelly. No 512x512px exists:

https://info.shelly.cloud/media-assets/

**Comment by walkxcode** [comment]
Quality is too low. Feel free to re-open if you can provide a better one.
