### ISSUE TITLE
Add Dockge Icon

### ISSUE THREAD

**Issue by Tenyun** [walkxcode/dashboard-icons#697]
### Contribution Guidelines

- [X] I have read and agree to the [Contribution Guidelines](https://github.com/walkxcode/dashboard-icons/blob/main/CONTRIBUTING.md)

### Icon Name

dockge

### Icon(s)

https://github.com/louislam/dockge/raw/master/frontend/public/icon.svg

**Comment by walkxcode** [comment]
https://github.com/walkxcode/dashboard-icons/blob/main/png/dockge.png
