### ISSUE TITLE
[Icon Request]: Speedtest-tracker

### ISSUE THREAD

**Issue by mcrutherford** [WalkxCode/dashboard-icons#7]
**What is the name of the icon?**
Speedtest-tracker

**What is the website/page of the icon?**
https://github.com/henrywhitaker3/Speedtest-Tracker

**Upload the icon here: [Optional]**
![speedtest-tracker](https://user-images.githubusercontent.com/23453492/133098118-4aecb107-bd58-4d3d-bb1f-d9b1d730e3d9.png)

**Comment by WalkxCode** [comment]
I'm gonna try to find a better quality version of it. If I can't find one I'll add it!

**Comment by WalkxCode** [comment]
The icon has been added!
