### ISSUE TITLE
Add Whoogle

### ISSUE THREAD

**Issue by DevSecNinja** [walkxcode/dashboard-icons#704]
### Contribution Guidelines

- [X] I have read and agree to the [Contribution Guidelines](https://github.com/walkxcode/dashboard-icons/blob/main/CONTRIBUTING.md)

### Icon Name

whoogle

### Icon(s)

![apple-icon](https://github.com/walkxcode/dashboard-icons/assets/14926452/47378f74-f31f-492f-895f-efe7b2e307f7)
Source: https://github.com/benbusby/whoogle-search/blob/main/app/static/img/favicon/apple-icon.png

There doesn't seem to be an SVG available nor one that adheres to the 512px height requirement.

**Comment by walkxcode** [comment]
https://github.com/walkxcode/dashboard-icons/blob/main/png/whooglesearch.png. Will add a version named `whoogle`.

**Comment by DevSecNinja** [comment]
Cheers, thanks!
