### ISSUE TITLE
Add Shelly S

### ISSUE THREAD

**Issue by tutomun** [walkxcode/dashboard-icons#728]
### Contribution Guidelines

- [X] I have read and agree to the [Contribution Guidelines](https://github.com/walkxcode/dashboard-icons/blob/main/CONTRIBUTING.md)

### Icon Name

shelly-s.png

### Icon(s)

![shelly-s](https://github.com/walkxcode/dashboard-icons/assets/33230248/a2579be2-464f-4e89-8d3b-dd0bcd99ab9a)

**Comment by walkxcode** [comment]
Hi, this logo is not used anymore so will not be added.
