### ISSUE TITLE
myspeed

### ISSUE THREAD

**Issue by stanthewizzard** [walkxcode/dashboard-icons#762]
### Contribution Guidelines

- [X] I have read and agree to the [Contribution Guidelines](https://github.com/walkxcode/dashboard-icons/blob/main/CONTRIBUTING.md)

### Icon Name

myspeed

### Icon(s)

https://github.com/gnmyt/myspeed

Thanks

**Comment by manelrodero** [comment]
Hello,

Any news on this icon?

In the meantime, I'm using the one that's on the project GitHub page:

https://camo.githubusercontent.com/4ccc83cf6b1f06e999c378bda264433ec83994031c156a5c88876b53eb57b201/68747470733a2f2f692e696d6775722e636f6d2f61436d413672482e706e67

**Comment by walkxcode** [comment]
Added in https://github.com/walkxcode/dashboard-icons/commit/88e984ddaf001bb4454dd7ca18fdb654db187015
