### ISSUE TITLE
⚡ — Dell Icon

### ISSUE THREAD

**Issue by dropsignal** [walkxcode/Dashboard-Icons#80]
### Type

Icon request

### Info

Please add the Dell icon for web-based administration utilities like iDRAC. Thank you!

### Icon(s)

![dell_logo](https://user-images.githubusercontent.com/34486773/195710346-838d1254-adaf-4f54-a06a-67b19b964023.jpg)

**Comment by tmeuze** [comment]
@dropsignal A Dell icon exists as "[idrac](https://github.com/walkxcode/Dashboard-Icons/blob/main/png/idrac.png)"

**Comment by dropsignal** [comment]
My apologies. I did not see that. Thank you for pointing that out.
