### ISSUE TITLE
⚡ — *Icon Request for CheckMK*

### ISSUE THREAD

**Issue by bmcgonag** [walkxcode/Dashboard-Icons#88]
### Type

Icon request

### Info

CheckMK is an open source project that provides monitoring for systems, networks, and so on.  https://checkmk.com/

### Icon(s)

![checkmk](https://user-images.githubusercontent.com/7346620/196509126-9cfccc32-8078-4b2a-833e-e2d7e4cad5e5.png)

**Comment by walkxcode** [comment]
Heya, CheckMK should already be in the repo! https://github.com/walkxcode/Dashboard-Icons/blob/main/png/checkmk.png
